language: csharp
solution: Snowflake.sln
install:
  - sudo mozroots --import --sync
  - ls
  - mono ./.nuget/NuGet.exe restore Snowflake.sln
  - mono ./.nuget/NuGet.exe install xunit.runners -Version 2.0.0-rc1-build2826 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug Snowflake.sln
notifications:
  irc:
    channels:
      - "irc.stormbit.net#snowflake"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: true
