language: csharp
sudo: false
solution: Snowflake.sln
mono:
  - nightly
install:
  - nuget restore ./Snowflake.sln

script:
  - xbuild /p:Configuration=Debug Snowflake.sln /tv:14.0
notifications:
  irc:
    channels:
      - "irc.stormbit.net#snowflake"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: true
  webhooks: http://fure-kun.herokuapp.com/hubot/travis?room=%23snowflake
